### PR TITLE
Added TypeScript support

### PR DESCRIPTION
**Pull request by 9renpoto**
- Added travis-ci & jest tests
- Added type definitions
- Added coverage report
- https://travis-ci.com/9renpoto/react-router-ga
- https://codecov.io/gh/9renpoto/react-router-ga/branch/feature%2Ftypings

### CODE REVIEW

**Comment by 9renpoto** [comment]
@fknussel Hi, please review it. Thank you .

**Comment by 9renpoto** [comment]
😢

**Comment by fknussel** [comment]
Hi @9renpoto, thanks for your PR :)

Here's an interesting read on adding TS type definitions support to a project like this: https://www.triplet.fi/blog/three-ways-to-provide-typescript-type-definitions-to-3rd-party-libraries/

From all your changes, reckon we can get away with the `index.d.ts` file only.

More than happy to have another look if you have time to clean this up.

Thanks again!

**Comment by 9renpoto** [comment]
thank you for your review! 

This change includes testing to improve the quality of the product, and testing of type definition. Will this library be introduced and improved continuously from now on?

Refers to DefinitlyTyled for creating type definition file.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Also, if continuous maintenance is not planned, we will refrain from using it in production.

thank you :)

**Pull request closed without merging**
